import { IMovie } from "@models/movie/IMovie";

export const moviesImdbNew: IMovie[] = [
  {
    id: "tt6718170",
    title: "The Super Mario Bros. Movie",
    fullTitle: "The Super Mario Bros. Movie (2023)",
    year: "2023",
    releaseState: "05 Apr 2023",
    image:
      "https://m.media-amazon.com/images/M/MV5BOTJhNzlmNzctNTU5Yy00N2YwLThhMjQtZDM0YjEzN2Y0ZjNhXkEyXkFqcGdeQXVyMTEwMTQ4MzU5._V1_Ratio0.6699_AL_.jpg",
    runtimeMins: "92",
    runtimeStr: "92 mins",
    plot: "The story of The Super Mario Bros. on their journey through the Mushroom Kingdom.",
    contentRating: "PG",
    imDbRating: "7.4",
    imDbRatingCount: "37027",
    metacriticRating: "46",
    genres: "Animation, Adventure, Comedy",
    directors: "Aaron Horvath, Michael Jelenic, Pierre Leduc, Fabien Polack",
    stars: "Chris Pratt, Anya Taylor-Joy, Charlie Day, Jack Black",
  },
  {
    id: "tt2906216",
    title: "Dungeons & Dragons: Honor Among Thieves",
    fullTitle: "Dungeons & Dragons: Honor Among Thieves (2023)",
    year: "2023",
    releaseState: "31 Mar 2023",
    image:
      "https://m.media-amazon.com/images/M/MV5BZjAyMGMwYTEtNDk4ZS00YmY0LThhZjUtOWI4ZjFmZmU4N2I3XkEyXkFqcGdeQXVyMTEyNzQ1MTk0._V1_Ratio0.6794_AL_.jpg",
    runtimeMins: "134",
    runtimeStr: "134 mins",
    plot: "A charming thief and a band of unlikely adventurers embark on an epic quest to retrieve a lost relic, but things go dangerously awry when they run afoul of the wrong people.",
    contentRating: "PG-13",
    imDbRating: "7.6",
    imDbRatingCount: "35617",
    metacriticRating: "72",
    genres: "Action, Adventure, Comedy",
    directors: "John Francis Daley, Jonathan Goldstein",
    stars: "Chris Pine, Michelle Rodriguez, Regé-Jean Page, Justice Smith",
  },
  {
    id: "tt10366206",
    title: "John Wick: Chapter 4",
    fullTitle: "John Wick: Chapter 4 (2023)",
    year: "2023",
    releaseState: "24 Mar 2023",
    image:
      "https://m.media-amazon.com/images/M/MV5BMDExZGMyOTMtMDgyYi00NGIwLWJhMTEtOTdkZGFjNmZiMTEwXkEyXkFqcGdeQXVyMjM4NTM5NDY@._V1_Ratio0.6699_AL_.jpg",
    runtimeMins: "169",
    runtimeStr: "169 mins",
    plot: "John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.",
    contentRating: "R",
    imDbRating: "8.3",
    imDbRatingCount: "106257",
    metacriticRating: "78",
    genres: "Action, Crime, Thriller",
    directors: "Chad Stahelski",
    stars: "Keanu Reeves, Laurence Fishburne, George Georgiou, Lance Reddick",
  },
  {
    id: "tt16419074",
    title: "Air",
    fullTitle: "Air (2023)",
    year: "2023",
    releaseState: "05 Apr 2023",
    image:
      "https://m.media-amazon.com/images/M/MV5BYmNlOTNlYjUtM2U3Yy00M2ZjLTkxZDQtN2NiNGZiZDI0ZjE3XkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_Ratio0.6699_AL_.jpg",
    runtimeMins: "111",
    runtimeStr: "111 mins",
    plot: "Follows the history of shoe salesman Sonny Vaccaro, and how he led Nike in its pursuit of the greatest athlete in the history of basketball, Michael Jordan.",
    contentRating: "R",
    imDbRating: "7.8",
    imDbRatingCount: "10332",
    metacriticRating: "73",
    genres: "Drama, Sport",
    directors: "Ben Affleck",
    stars: "Matt Damon, Jason Bateman, Ben Affleck, Chris Messina",
  },
  {
    id: "tt1630029",
    title: "Avatar: The Way of Water",
    fullTitle: "Avatar: The Way of Water (2022)",
    year: "2022",
    releaseState: "16 Dec 2022",
    image:
      "https://m.media-amazon.com/images/M/MV5BYjhiNjBlODctY2ZiOC00YjVlLWFlNzAtNTVhNzM1YjI1NzMxXkEyXkFqcGdeQXVyMjQxNTE1MDA@._V1_Ratio0.6986_AL_.jpg",
    runtimeMins: "192",
    runtimeStr: "192 mins",
    plot: "Jake Sully lives with his newfound family formed on the extrasolar moon Pandora. Once a familiar threat returns to finish what was previously started, Jake must work with Neytiri and the army of the Na'vi race to protect their home.",
    contentRating: "PG-13",
    imDbRating: "7.7",
    imDbRatingCount: "349790",
    metacriticRating: "67",
    genres: "Action, Adventure, Fantasy",
    directors: "James Cameron",
    stars: "Sam Worthington, Zoe Saldana, Sigourney Weaver, Stephen Lang",
  },
  {
    id: "tt11145118",
    title: "Creed III",
    fullTitle: "Creed III (2023)",
    year: "2023",
    releaseState: "03 Mar 2023",
    image:
      "https://m.media-amazon.com/images/M/MV5BYWY1ZDY4MmQtYjhiYS00N2QwLTk1NzgtOWI2YzUwZThjNDYwXkEyXkFqcGdeQXVyMDM2NDM2MQ@@._V1_Ratio0.6699_AL_.jpg",
    runtimeMins: "116",
    runtimeStr: "116 mins",
    plot: "Adonis has been thriving in both his career and family life, but when a childhood friend and former boxing prodigy resurfaces, the face-off is more than just a fight.",
    contentRating: "PG-13",
    imDbRating: "7",
    imDbRatingCount: "43584",
    metacriticRating: "73",
    genres: "Drama, Sport",
    directors: "Michael B. Jordan",
    stars: "Michael B. Jordan, Tessa Thompson, Jonathan Majors, Wood Harris",
  },
  {
    id: "tt10151854",
    title: "Shazam! Fury of the Gods",
    fullTitle: "Shazam! Fury of the Gods (2023)",
    year: "2023",
    releaseState: "17 Mar 2023",
    image:
      "https://m.media-amazon.com/images/M/MV5BNzJlM2NmZTItOGQyYS00MmE2LTkwZGUtNDFkNmJmZjRjZjcxXkEyXkFqcGdeQXVyMTA3MDk2NDg2._V1_Ratio0.6699_AL_.jpg",
    runtimeMins: "130",
    runtimeStr: "130 mins",
    plot: 'The film continues the story of teenage Billy Batson who, upon reciting the magic word "SHAZAM!" is transformed into his adult Super Hero alter ego, Shazam.',
    contentRating: "PG-13",
    imDbRating: "6.2",
    imDbRatingCount: "41450",
    metacriticRating: "47",
    genres: "Action, Adventure, Comedy",
    directors: "David F. Sandberg",
    stars: "Zachary Levi, Asher Angel, Jack Dylan Grazer, Rachel Zegler",
  },
  {
    id: "tt6710474",
    title: "Everything Everywhere All at Once",
    fullTitle: "Everything Everywhere All at Once (2022)",
    year: "2022",
    releaseState: "08 Apr 2022",
    image:
      "https://m.media-amazon.com/images/M/MV5BYTdiOTIyZTQtNmQ1OS00NjZlLWIyMTgtYzk5Y2M3ZDVmMDk1XkEyXkFqcGdeQXVyMTAzMDg4NzU0._V1_Ratio0.6890_AL_.jpg",
    runtimeMins: "139",
    runtimeStr: "139 mins",
    plot: "A middle-aged Chinese immigrant is swept up into an insane adventure in which she alone can save existence by exploring other universes and connecting with the lives she could have led.",
    contentRating: "R",
    imDbRating: "7.9",
    imDbRatingCount: "422954",
    metacriticRating: "81",
    genres: "Action, Adventure, Comedy",
    directors: "Daniel Kwan, Daniel Scheinert",
    stars: "Michelle Yeoh, Stephanie Hsu, Jamie Lee Curtis, Ke Huy Quan",
  },
  {
    id: "tt12261776",
    title: "65",
    fullTitle: "65 (2023)",
    year: "2023",
    releaseState: "10 Mar 2023",
    image:
      "https://m.media-amazon.com/images/M/MV5BYzFhM2M1MDUtNDhmNC00YzEzLThiMzctYWYxZTc0MGJhNWYyXkEyXkFqcGdeQXVyMTUzMTg2ODkz._V1_Ratio0.7943_AL_.jpg",
    runtimeMins: "93",
    runtimeStr: "93 mins",
    plot: "An astronaut crash lands on a mysterious planet only to discover he's not alone.",
    contentRating: "PG-13",
    imDbRating: "5.5",
    imDbRatingCount: "24978",
    metacriticRating: "40",
    genres: "Action, Adventure, Drama",
    directors: "Scott Beck, Bryan Woods",
    stars: "Adam Driver, Ariana Greenblatt, Chloe Coleman, Nika King",
  },
  {
    id: "tt17663992",
    title: "Scream VI",
    fullTitle: "Scream VI (2023)",
    year: "2023",
    releaseState: "10 Mar 2023",
    image:
      "https://m.media-amazon.com/images/M/MV5BODBjM2M4YTQtNmJlMS00MGU2LWI4ZGYtZTA1MzdmZDAyMjFkXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_Ratio0.6699_AL_.jpg",
    runtimeMins: "122",
    runtimeStr: "122 mins",
    plot: "In the next installment, the survivors of the Ghostface killings leave Woodsboro behind and start a fresh chapter in New York City.",
    contentRating: "R",
    imDbRating: "7.1",
    imDbRatingCount: "40690",
    metacriticRating: "61",
    genres: "Horror, Mystery, Thriller",
    directors: "Matt Bettinelli-Olpin, Tyler Gillett",
    stars: "Courteney Cox, Melissa Barrera, Jenna Ortega, Jasmin Savoy Brown",
  },
  {
    id: "tt14209916",
    title: "Cocaine Bear",
    fullTitle: "Cocaine Bear (2023)",
    year: "2023",
    releaseState: "24 Feb 2023",
    image:
      "https://m.media-amazon.com/images/M/MV5BODAwZDQ5ZjEtZDI1My00MTFiLTg0ZjUtOGE2YTBkOTdjODFhXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_Ratio0.6699_AL_.jpg",
    runtimeMins: "95",
    runtimeStr: "95 mins",
    plot: "An oddball group of cops, criminals, tourists and teens converge on a Georgia forest where a huge black bear goes on a murderous rampage after unintentionally ingesting cocaine.",
    contentRating: "R",
    imDbRating: "6",
    imDbRatingCount: "50224",
    metacriticRating: "54",
    genres: "Comedy, Thriller",
    directors: "Elizabeth Banks",
    stars: "Keri Russell, Alden Ehrenreich, O'Shea Jackson Jr., Ray Liotta",
  },
  {
    id: "tt8277246",
    title: "His Only Son",
    fullTitle: "His Only Son (2023)",
    year: "2023",
    releaseState: "30 Mar 2023",
    image:
      "https://m.media-amazon.com/images/M/MV5BZTU5MTY4OGMtYTRiMS00ZTA1LThmMGQtOWQ4YzE4NThlYjljXkEyXkFqcGdeQXVyNzYzMjAyMzU@._V1_Ratio0.6699_AL_.jpg",
    runtimeMins: "106",
    runtimeStr: "106 mins",
    plot: "After being called on by the Lord, Abraham's faith is tested on his three day journey to sacrifice his son.",
    contentRating: "PG-13",
    imDbRating: "6.4",
    imDbRatingCount: "850",
    metacriticRating: "",
    genres: "Drama, History",
    directors: "David Helling",
    stars: "Nicolas Mouawad, Sara Seyed, Daniel da Silva, Edaan Moskowitz",
  },
  {
    id: "tt10954600",
    title: "Ant-Man and the Wasp: Quantumania",
    fullTitle: "Ant-Man and the Wasp: Quantumania (2023)",
    year: "2023",
    releaseState: "17 Feb 2023",
    image:
      "https://m.media-amazon.com/images/M/MV5BODZhNzlmOGItMWUyYS00Y2Q5LWFlNzMtM2I2NDFkM2ZkYmE1XkEyXkFqcGdeQXVyMTU5OTA4NTIz._V1_Ratio0.6699_AL_.jpg",
    runtimeMins: "124",
    runtimeStr: "124 mins",
    plot: "Scott Lang and Hope Van Dyne, along with Hank Pym and Janet Van Dyne, explore the Quantum Realm, where they interact with strange creatures and embark on an adventure that goes beyond the limits of what they thought was possible.",
    contentRating: "PG-13",
    imDbRating: "6.4",
    imDbRatingCount: "97736",
    metacriticRating: "48",
    genres: "Action, Adventure, Comedy",
    directors: "Peyton Reed",
    stars: "Paul Rudd, Evangeline Lilly, Michael Douglas, Michelle Pfeiffer",
  },
  {
    id: "tt14153080",
    title: "A Good Person",
    fullTitle: "A Good Person (2023)",
    year: "2023",
    releaseState: "24 Mar 2023",
    image:
      "https://m.media-amazon.com/images/M/MV5BYzBkZGYyM2QtNzgwYy00NmZjLTk2ZTItYzY3ZTdjY2M0YmQwXkEyXkFqcGdeQXVyMjkwOTAyMDU@._V1_Ratio0.6699_AL_.jpg",
    runtimeMins: "128",
    runtimeStr: "128 mins",
    plot: "Follows Allison, whose life falls apart following her involvement in a fatal accident.",
    contentRating: "R",
    imDbRating: "7.1",
    imDbRatingCount: "1626",
    metacriticRating: "50",
    genres: "Drama",
    directors: "Zach Braff",
    stars: "Florence Pugh, Morgan Freeman, Celeste O'Connor, Molly Shannon",
  },
  {
    id: "tt14472156",
    title: "Paint",
    fullTitle: "Paint (2023)",
    year: "2023",
    releaseState: "07 Apr 2023",
    image:
      "https://m.media-amazon.com/images/M/MV5BMWFmOTU2ZjctN2VhMS00Yzg4LWIyOGEtMTgwZTdjYTMyZjNkXkEyXkFqcGdeQXVyMzQwMTY2Nzk@._V1_Ratio0.6699_AL_.jpg",
    runtimeMins: "96",
    runtimeStr: "96 mins",
    plot: "Carl Nargle, Vermont's #1 public television painter, is convinced he has it all: a signature perm, custom van, and fans hanging on his every stroke - until a younger, better artist steals everything (and everyone) Carl loves.",
    contentRating: "PG-13",
    imDbRating: "6.1",
    imDbRatingCount: "259",
    metacriticRating: "45",
    genres: "Comedy, Drama",
    directors: "Brit McAdams",
    stars: "Owen Wilson, Elisabeth Henry, Paul Kosopod, Sonia Darmei Lopes",
  },
  {
    id: "tt12427158",
    title: "A Thousand and One",
    fullTitle: "A Thousand and One (2023)",
    year: "2023",
    releaseState: "31 Mar 2023",
    image:
      "https://m.media-amazon.com/images/M/MV5BYTM4Y2FhODgtMjU2Yy00NzNjLWI3MTYtM2I3ZTRmYzczYzc0XkEyXkFqcGdeQXVyMTA3MDk2NDg2._V1_Ratio0.6699_AL_.jpg",
    runtimeMins: "117",
    runtimeStr: "117 mins",
    plot: "After unapologetic and fiercely loyal Inez kidnaps her son Terry from the foster care system, mother and son set out to reclaim their sense of home, identity, and stability, in a rapidly changing New York City.",
    contentRating: "R",
    imDbRating: "7.4",
    imDbRatingCount: "854",
    metacriticRating: "80",
    genres: "Crime, Drama",
    directors: "A.V. Rockwell",
    stars: "Teyana Taylor, Aaron Kingsley Adetola, Aven Courtney, Josiah Cross",
  },
  {
    id: "tt10098448",
    title: "Jesus Revolution",
    fullTitle: "Jesus Revolution (2023)",
    year: "2023",
    releaseState: "24 Feb 2023",
    image:
      "https://m.media-amazon.com/images/M/MV5BZjQ4M2JiMTEtNDhiMi00OWM1LTkwMWEtODdjYTQxNWQyOTFiXkEyXkFqcGdeQXVyMjMxOTE0ODA@._V1_Ratio0.6699_AL_.jpg",
    runtimeMins: "120",
    runtimeStr: "120 mins",
    plot: "The true story of a national spiritual awakening in the early 1970s and its origins within a community of teenage hippies in Southern California.",
    contentRating: "PG-13",
    imDbRating: "7.6",
    imDbRatingCount: "5083",
    metacriticRating: "46",
    genres: "Drama",
    directors: "Jon Erwin, Brent McCorkle",
    stars:
      "Joel Courtney, Jonathan Roumie, Kimberly Williams-Paisley, Anna Grace Barlow",
  },
  {
    id: "tt0166924",
    title: "Mulholland Drive",
    fullTitle: "Mulholland Drive (2001)",
    year: "2001",
    releaseState: "19 Oct 2001",
    image:
      "https://m.media-amazon.com/images/M/MV5BYTRiMzg4NDItNTc3Zi00NjBjLTgwOWYtOGZjMTFmNGU4ODY4XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_Ratio0.6699_AL_.jpg",
    runtimeMins: "147",
    runtimeStr: "147 mins",
    plot: "After a car wreck on the winding Mulholland Drive renders a woman amnesiac, she and a perky Hollywood-hopeful search for clues and answers across Los Angeles in a twisting venture beyond dreams and reality.",
    contentRating: "R",
    imDbRating: "7.9",
    imDbRatingCount: "364441",
    metacriticRating: "86",
    genres: "Drama, Mystery, Thriller",
    directors: "David Lynch",
    stars: "Naomi Watts, Laura Harring, Justin Theroux, Jeanne Bates",
  },
  {
    id: "tt15440322",
    title: "Dasara",
    fullTitle: "Dasara (2023)",
    year: "2023",
    releaseState: "31 Mar 2023",
    image:
      "https://m.media-amazon.com/images/M/MV5BMzgwMGZlZmUtNThiYi00OGJkLWE1YjMtMmY3NDIzYTk5NDNiXkEyXkFqcGdeQXVyMTA5MjQ4MDg4._V1_Ratio0.6699_AL_.jpg",
    runtimeMins: "156",
    runtimeStr: "156 mins",
    plot: "Set in the backdrop of Singareni coal mines near Godavarikhani of Telangana.",
    contentRating: "",
    imDbRating: "7.5",
    imDbRatingCount: "4613",
    metacriticRating: "",
    genres: "Action, Adventure, Drama",
    directors: "Srikanth Odela",
    stars: "Nani, Keerthy Suresh, Shine Tom Chacko, Dheekshith Shetty",
  },
  {
    id: "tt13923456",
    title: "Mafia Mamma",
    fullTitle: "Mafia Mamma (2023)",
    year: "2023",
    releaseState: "14 Apr 2023",
    image:
      "https://m.media-amazon.com/images/M/MV5BNDg0YmQ0NDMtNzdmYi00OTA5LWFjZDEtMWQ5NTQ0NjM4YTRlXkEyXkFqcGdeQXVyMTA3MDk2NDg2._V1_Ratio0.6699_AL_.jpg",
    runtimeMins: "101",
    runtimeStr: "101 mins",
    plot: "An American mom inherits her grandfather's mafia empire in Italy. Guided by the firm's consigliere, she hilariously defies everyone's expectations as the new head of the family business.",
    contentRating: "R",
    imDbRating: "",
    imDbRatingCount: "",
    metacriticRating: "",
    genres: "Action, Comedy, Crime",
    directors: "Catherine Hardwicke",
    stars:
      "Toni Collette, Monica Bellucci, Sophia Nomvete, Alessandro Bressanello",
  },
  {
    id: "tt11396310",
    title: "Viduthalai Part-1",
    fullTitle: "Viduthalai Part-1 (2023)",
    year: "2023",
    releaseState: "31 Mar 2023",
    image:
      "https://m.media-amazon.com/images/M/MV5BYThhYzA0ZDktNTkzOC00Mjk1LTg0ZmYtYzFhNGI0ZjEyM2U0XkEyXkFqcGdeQXVyMTEzNzg0Mjkx._V1_Ratio0.6986_AL_.jpg",
    runtimeMins: "150",
    runtimeStr: "150 mins",
    plot: "A police officer is recruited to capture the leader of a separatist group.",
    contentRating: "",
    imDbRating: "8.7",
    imDbRatingCount: "2694",
    metacriticRating: "",
    genres: "Action, Crime, Drama",
    directors: "Vetrimaaran",
    stars: "Soori, Vijay Sethupathi, Bhavani Sre, Chetan",
  },
  {
    id: "tt21440780",
    title: "How to Blow Up a Pipeline",
    fullTitle: "How to Blow Up a Pipeline (2022)",
    year: "2022",
    releaseState: "07 Apr 2023",
    image:
      "https://m.media-amazon.com/images/M/MV5BYmQyOGQxMGQtNzVjMy00ZmQ2LTg5NzAtZTNkNDMzODkyZDgzXkEyXkFqcGdeQXVyMTA2MDU0NjM5._V1_Ratio0.6699_AL_.jpg",
    runtimeMins: "103",
    runtimeStr: "103 mins",
    plot: "A crew of environmental activists plot a daring plan to disrupt an oil pipeline.",
    contentRating: "R",
    imDbRating: "7.3",
    imDbRatingCount: "558",
    metacriticRating: "76",
    genres: "Crime, Drama, Thriller",
    directors: "Daniel Goldhaber",
    stars: "Ariela Barer, Kristine Froseth, Lukas Gage, Forrest Goodluck",
  },
  {
    id: "tt13421498",
    title: "The Lost King",
    fullTitle: "The Lost King (2022)",
    year: "2022",
    releaseState: "24 Mar 2023",
    image:
      "https://m.media-amazon.com/images/M/MV5BOTNiMWE2NWEtYjViMC00ZWI1LWJiMzgtNGU2ZmVkMGNkYTU2XkEyXkFqcGdeQXVyMTk5MTY4Nzg@._V1_Ratio0.6699_AL_.jpg",
    runtimeMins: "108",
    runtimeStr: "108 mins",
    plot: "An amateur historian defies the stodgy academic establishment in her efforts to find King Richard III's remains, which were lost for over 500 years.",
    contentRating: "PG-13",
    imDbRating: "6.6",
    imDbRatingCount: "3599",
    metacriticRating: "64",
    genres: "Comedy, Drama",
    directors: "Stephen Frears",
    stars: "Sally Hawkins, Shonagh Price, Helen Katamba, Lewis Macleod",
  },
  {
    id: "tt15430628",
    title: "Ride On",
    fullTitle: "Ride On (2023)",
    year: "2023",
    releaseState: "07 Apr 2023",
    image:
      "https://m.media-amazon.com/images/M/MV5BMzVhZDU0MTQtNzkzOS00NjRlLWE5NGEtYWQ2YWJjZWZlYTkzXkEyXkFqcGdeQXVyMTUzMDA3Mjc2._V1_Ratio0.6890_AL_.jpg",
    runtimeMins: "126",
    runtimeStr: "126 mins",
    plot: "A washed-up stuntman and his stunt horse become an overnight social media sensation when their real-life fight with debt collectors goes viral.",
    contentRating: "",
    imDbRating: "7.1",
    imDbRatingCount: "71",
    metacriticRating: "",
    genres: "Action, Comedy, Drama",
    directors: "Larry Yang",
    stars: "Jackie Chan, Haocun Liu, Kevin Guo, Yueting Lang",
  },
  {
    id: "tt11698800",
    title: "Enys Men",
    fullTitle: "Enys Men (2022)",
    year: "2022",
    releaseState: "18 Apr 2023",
    image:
      "https://m.media-amazon.com/images/M/MV5BOThmY2FlYmQtYTM4OS00MWM5LThiNGMtNjExYjQ2NjExZmViXkEyXkFqcGdeQXVyMTMwODM2ODM@._V1_Ratio0.6699_AL_.jpg",
    runtimeMins: "91",
    runtimeStr: "91 mins",
    plot: "Set in 1973 on an uninhabited island off the Cornish coast, a wildlife volunteer's daily observations of a rare flower turn into a metaphysical journey that forces her as well as the viewer to question what is real and what is nightmare.",
    contentRating: "",
    imDbRating: "6.2",
    imDbRatingCount: "886",
    metacriticRating: "78",
    genres: "Horror",
    directors: "Mark Jenkin",
    stars: "Mary Woodvine, Edward Rowe, Flo Crowe, John Woodvine",
  },
  {
    id: "tt19719836",
    title: "Return to Seoul",
    fullTitle: "Return to Seoul (2022)",
    year: "2022",
    releaseState: "18 Nov 2022",
    image:
      "https://m.media-amazon.com/images/M/MV5BN2I0ZTc5MjktMDllYi00MTNhLTg5YzMtZmQxYWNkYzUzYTAyXkEyXkFqcGdeQXVyMTQyODg5MjQw._V1_Ratio0.6699_AL_.jpg",
    runtimeMins: "119",
    runtimeStr: "119 mins",
    plot: "A twenty-five-year-old French woman returns to Korea, the country she was born in before being adopted by a French couple, for the very first time. She decides to track down her biological parents, but her journey takes a surprising turn.",
    contentRating: "R",
    imDbRating: "7.1",
    imDbRatingCount: "1504",
    metacriticRating: "87",
    genres: "Drama",
    directors: "Davy Chou",
    stars: "Park Ji-min, Oh Kwang-rok, Guka Han, Kim Sun-young",
  },
  {
    id: "tt15488088",
    title: "Moving On (III)",
    fullTitle: "Moving On (III) (2022)",
    year: "2022",
    releaseState: "08 Jan 2023",
    image:
      "https://m.media-amazon.com/images/M/MV5BMzMyZDk0YWMtZmQ2OC00NTExLTgxM2ItZTkzM2I3YTBjMTM2XkEyXkFqcGdeQXVyMTAyMjQ3NzQ1._V1_Ratio0.6794_AL_.jpg",
    runtimeMins: "85",
    runtimeStr: "85 mins",
    plot: "Two old friends reconnect at a funeral and decide to get revenge on the widower who messed with them decades before.",
    contentRating: "R",
    imDbRating: "6.4",
    imDbRatingCount: "375",
    metacriticRating: "60",
    genres: "Comedy",
    directors: "Paul Weitz",
    stars: "Jane Fonda, Lily Tomlin, Malcolm McDowell, Lauren Tom",
  },
  {
    id: "tt16301792",
    title: "La Usurpadora: The Musical",
    fullTitle: "La Usurpadora: The Musical (2023)",
    year: "2023",
    releaseState: "12 Apr 2023",
    image:
      "https://m.media-amazon.com/images/M/MV5BOGEzNjAxODctMTJkZC00YjNlLWFiNmYtODA3YTA2NmM3ZGFhXkEyXkFqcGdeQXVyMTAwMTI1Njk4._V1_Ratio0.6794_AL_.jpg",
    runtimeMins: "115",
    runtimeStr: "115 mins",
    plot: "Two identical twin sisters, separated at birth, one truly decent but humble, the other ultra rich, conniving, and truly destructive. They soon find themselves hopelessly intertwined in each other's lives.",
    contentRating: "PG-13",
    imDbRating: "8.2",
    imDbRatingCount: "24",
    metacriticRating: "",
    genres: "Comedy, Crime, Musical",
    directors: "Santiago Limón",
    stars:
      "Isabella Castillo, Alan Estrada, Cecilia Toussaint, Susana Zabaleta",
  },
  {
    id: "tt15816190",
    title: "Ravanasura",
    fullTitle: "Ravanasura (2023)",
    year: "2023",
    releaseState: "07 Apr 2023",
    image:
      "https://m.media-amazon.com/images/M/MV5BZmRlNGYwMWUtZGMzMS00NmEyLTk0YjAtM2M1NDJmM2VkMTg4XkEyXkFqcGdeQXVyNTgxODY5ODI@._V1_Ratio0.6794_AL_.jpg",
    runtimeMins: "141",
    runtimeStr: "141 mins",
    plot: "Ravanasura is an upcoming Indian Telugu language psychological action thriller film directed by Sudheer Varma from a story written by Srikanth Vissa.",
    contentRating: "",
    imDbRating: "6.9",
    imDbRatingCount: "636",
    metacriticRating: "",
    genres: "Action, Crime, Drama",
    directors: "Sudheer Varma",
    stars: "Jayaram, Faria Abdullah, Megha Akash, Jahid D'cruz",
  },
  {
    id: "tt13885492",
    title: "Little Richard: I Am Everything",
    fullTitle: "Little Richard: I Am Everything (2023)",
    year: "2023",
    releaseState: "21 Apr 2023",
    image:
      "https://m.media-amazon.com/images/M/MV5BNjU5YzNiM2QtZmFhNS00NjI2LWEwNzItN2NmYzFhZjIwNzFmXkEyXkFqcGdeQXVyNjUxMjc1OTM@._V1_Ratio0.6699_AL_.jpg",
    runtimeMins: "101",
    runtimeStr: "101 mins",
    plot: "One of a kind rock 'n' roll icon who shaped the world of music.",
    contentRating: "",
    imDbRating: "7.7",
    imDbRatingCount: "72",
    metacriticRating: "79",
    genres: "Documentary, Music",
    directors: "Lisa Cortes",
    stars: "John Waters, Mick Jagger, Paul McCartney, Tom Jones",
  },
  {
    id: "tt11455260",
    title: "School of Magical Animals",
    fullTitle: "School of Magical Animals (2021)",
    year: "2021",
    releaseState: "14 Oct 2021",
    image:
      "https://m.media-amazon.com/images/M/MV5BYjNiMDc3YzAtOTQ3ZS00M2M2LTlhYzktMmU3MzNhOWM2NTU4XkEyXkFqcGdeQXVyNzc0MTgzMzU@._V1_Ratio0.6699_AL_.jpg",
    runtimeMins: "93",
    runtimeStr: "93 mins",
    plot: "Ida must transfer to a new school, where she soon realizes the students are unkind to each other. However, that all changes when a new teacher, Miss Cornfield, begins to educate them on the value of friendship and magic.",
    contentRating: "PG",
    imDbRating: "5.3",
    imDbRatingCount: "530",
    metacriticRating: "",
    genres: "Adventure, Family",
    directors: "Gregor Schnitzler",
    stars: "Emilia Maier, Leonard Conrads, Loris Sichrovsky, Nadja Uhl",
  },
  {
    id: "tt19719940",
    title: "Rodeo (I)",
    fullTitle: "Rodeo (I) (2022)",
    year: "2022",
    releaseState: "07 Sep 2022",
    image:
      "https://m.media-amazon.com/images/M/MV5BOTk5ZmRmMjAtODQxMy00NzAwLWFlNTgtZjNmOTA3YjEyMGRjXkEyXkFqcGdeQXVyNDU0NjMyNTQ@._V1_Ratio0.6699_AL_.jpg",
    runtimeMins: "105",
    runtimeStr: "105 mins",
    plot: "Julia, a young misfit who is passionate about riding, meets a crew of dirt riders who fly along at full speed and perform stunts. She sets about infiltrating their male-dominated world, but an accident jeopardizes her ability to fit in.",
    contentRating: "",
    imDbRating: "6.1",
    imDbRatingCount: "371",
    metacriticRating: "69",
    genres: "Drama",
    directors: "Lola Quivoron",
    stars: "Julie Ledru, Yannis Lafki, Antonia Buresi, Cody Schroeder",
  },
  {
    id: "tt26234988",
    title: "Meter",
    fullTitle: "Meter (2023)",
    year: "2023",
    releaseState: "07 Apr 2023",
    image:
      "https://m.media-amazon.com/images/M/MV5BMDIxZTQ4NzktYzllNS00ZGFiLWJlOTctZmM0ZmQxNjQ0NTk3XkEyXkFqcGdeQXVyMTI1NDEyNTM5._V1_Ratio0.7464_AL_.jpg",
    runtimeMins: "127",
    runtimeStr: "127 mins",
    plot: "Arjun Kalyan reluctantly becomes a police officer to fulfill his father's dream, then an unexpected turn of events forces him to go head-to-head with the home minister of the state.",
    contentRating: "",
    imDbRating: "8.3",
    imDbRatingCount: "102",
    metacriticRating: "",
    genres: "Action, Comedy, Drama",
    directors: "Ramesh Kadhuri",
    stars:
      "Kiran Abbavaram, Athulya Ravi, Keshav Deepak, Krishna Murali Posani",
  },
  {
    id: "tt18690030",
    title: "Post Truth",
    fullTitle: "Post Truth (2022)",
    year: "2022",
    releaseState: "31 Dec 2022",
    image:
      "https://m.media-amazon.com/images/M/MV5BMTIwMTBhMGUtMjcyZS00N2IxLWI0YjQtMWFkNjFjODczODIyXkEyXkFqcGdeQXVyMTI5ODA1OTU0._V1_Ratio0.6699_AL_.jpg",
    runtimeMins: "112",
    runtimeStr: "112 mins",
    plot: "A cemetery salesman is slandered by rumors and his cemetery is facing demolition.",
    contentRating: "",
    imDbRating: "7",
    imDbRatingCount: "137",
    metacriticRating: "",
    genres: "Comedy, Drama",
    directors: "Chengpeng Dong",
    stars: "Chengpeng Dong, Xueqin Li, Zheng Yin, Xun Wang",
  },
  {
    id: "tt27079328",
    title: "Es Jahano Door Kitte Chal Jindiye",
    fullTitle: "Es Jahano Door Kitte Chal Jindiye (2023)",
    year: "2023",
    releaseState: "07 Apr 2023",
    image:
      "https://m.media-amazon.com/images/M/MV5BNjliNTliNmUtNDYwYS00NWRhLWFlMjgtZTU2OTcxMWY2YTBmXkEyXkFqcGdeQXVyMTYxNzk0Mzcy._V1_Ratio0.7943_AL_.jpg",
    runtimeMins: "134",
    runtimeStr: "134 mins",
    plot: "Depicts how different waves of migration have hit individuals who once left their homes with big dreams but are now only faced with challenges to returning home",
    contentRating: "",
    imDbRating: "8.4",
    imDbRatingCount: "576",
    metacriticRating: "",
    genres: "Drama",
    directors: "Uday Pratap Singh",
    stars: "Jass Bajwa, Neeru Bajwa, Kulwinder Billa, Gurpreet Ghuggi",
  },
  {
    id: "tt10646310",
    title: "Wings Over Water",
    fullTitle: "Wings Over Water (2022)",
    year: "2022",
    releaseState: "02 Jan 2022",
    image:
      "https://m.media-amazon.com/images/M/MV5BYTI0OTk5ZGQtOWNkZC00M2NkLTlkNjQtMTc0ZDM2ZGFjNjlmXkEyXkFqcGdeQXVyMTczMDYzMjA@._V1_Ratio0.6699_AL_.jpg",
    runtimeMins: "45",
    runtimeStr: "45 mins",
    plot: "A documentary filmed in stunning 3D high definition for IMAX. This film will showcase millions of migratory birds, the importance the wetlands of the upper midwest play in their lives, and ... See full summary",
    contentRating: "",
    imDbRating: "8.7",
    imDbRatingCount: "30",
    metacriticRating: "",
    genres: "Documentary",
    directors: "Andrew Young",
    stars: "Michael Keaton",
  },
];
