import { GetMovieReviewsResponse } from "@api/imdb/interfaces";

export const reviewsData: GetMovieReviewsResponse = {
  imDbId: "tt6718170",
  title: "The Super Mario Bros. Movie",
  fullTitle: "The Super Mario Bros. Movie (2023)",
  type: "Movie",
  year: "2023",
  items: [
    {
      username: "benjaminskylerhill",
      userUrl: "https://www.imdb.com/user/ur117768316",
      reviewLink: "https://www.imdb.com/review/rw8973426",
      warningSpoilers: false,
      date: "5 April 2023",
      rate: "7",
      helpful: "191 out of 225 found this helpful.",
      title: "Illumination's best since Despicable Me 1.",
      content:
        "Granted, this film is not going to appeal to people who have never been fans of any games featuring the titular brothers. But given the fact that these filmmakers were tasked with making a movie that caters to a fan base that spans four decades and thus have a myriad of tastes and expectations, they did a pretty good job. In fact, a slightly better job than I was expecting.The voice cast was the subject of much controversy, and I thought that for the most part it was actually spot-on. A couple of characters were horribly miscast in my opinion, but in particular Jack Black as Bowser and Charlie Day as Luigi shine as perfectly encapsulating the spirit of the characters.Platforming elements from the games was very efficiently worked into the action sequences, and some of them were quite thrilling. This is easily Illumination's most visually stunning film, and a massive step up from every one of their other films since the first Despicable Me.As for the plot, it's just the plot of every Mario game. And for the most part, that's all it needs to be. Every beat plays out almost exactly like you'd expect it to, with a couple subversions pleasantly thrown in there.The messiest parts of the movie, if I'm going to get critical, are the dialogue (which is often quite stupid) and the characters. They just try to deal with too many of them, and although four or five characters are strongly introduced with background and desires, almost none of these introductions actually amount to a payoff, and even when there is a payoff, it's haphazardly thrown together for a rushed ending.Although I think 85-90 minutes is actually the perfect length for an animated film normally, this one could've benefitted from an extra 10-20 minutes to flesh out these points a bit more. We move so quickly from location to location that there's never any time to breathe or get invested.But that's my adult perspective. I had a pretty breezy, fun, and heartwarming time, though I would've liked more meat on the script.My theater was PACKED, and probably 75% young children, and they all seemed to have the time of their lives. Your kids will probably love it, and you will probably more than tolerate it.",
    },
    {
      username: "justinvitelli",
      userUrl: "https://www.imdb.com/user/ur91786786",
      reviewLink: "https://www.imdb.com/review/rw8972952",
      warningSpoilers: false,
      date: "5 April 2023",
      rate: "10",
      helpful: "307 out of 376 found this helpful.",
      title: "An absolute BLAST!",
      content:
        "First off this movie is for kids and fans of Nintendo and the Mario franchise. I still think an adult who isnt a fan could still enjoy it but this movie is so full of fan service that it will have you smiling the whole time. The voice acting I was skeptical but they all work and work well too. Jack Black is the star here. I love how they kept the story simple like all of the games. Truly felt like a video game on screen. This movie felt like a beautifully animated amusement park ride. The audio in the movie was amazing too. The sounds and the score with reimagined iconic music was perfect. Some of the songs in the movie felt unnecessary but they worked. I think they should've bumped the run time to 105-120 min. 90 min felt too short as it goes by quick. I havent had this much wholesome fun at the movies in a long time. If youre a fan you HAVE to see it.",
    },
    {
      username: "nickryan-44535",
      userUrl: "https://www.imdb.com/user/ur88182480",
      reviewLink: "https://www.imdb.com/review/rw8973770",
      warningSpoilers: false,
      date: "5 April 2023",
      rate: "8",
      helpful: "128 out of 158 found this helpful.",
      title:
        "Everyone is so fixated on rotten tomatoes scores, it really is a solid film.",
      content:
        'I am someone who is not swayed by "critics" or rotten tomato scores. I didn\'t even really have any expectations going into this movie. As someone who grew up playing Super Mario Bros, Super Mario World etc., I was really just going to see this movie based on nostalgia and it does deliver on nostalgia. The visuals are stunning, and while everyone has their reservations about Chris Pratt the voice acting is perfect (except one for one elderly character). While many have said this movie moves quickly or "too fast", I would say it has great pacing and never leaves you bored. While it is not a perfect film it leaves little to be desired. It is everything you want from an animated Super Mario Movie.',
    },
    {
      username: "gabethedinosaur",
      userUrl: "https://www.imdb.com/user/ur33283012",
      reviewLink: "https://www.imdb.com/review/rw8974001",
      warningSpoilers: true,
      date: "6 April 2023",
      rate: "10",
      helpful: "152 out of 210 found this helpful.",
      title:
        "Chris Pratt was awesome as Mario and Jack black as bowser was remarkable!!!!!!",
      content:
        "After meeting Chris Pratt at the Santa Barbara film festival I'm very amazed of how remarkable Chris played Mario for the first. I remember playing Mario kart double dash on GameCube 20 years ago with my sister during Christmas Day and I absolutely loved the game . Universal and Nintendo did a great job making this movie for kids and adults who played the video game since the 80s 90s 2000s to now . The Mario movie was absolutely awesome and very creative from the video game . Chris was absolutely hilarious as Mario . Jack black as bowser was the best for the film. His voice was a mixture of Vader which I find so outstanding. Chris who voiced Mario did a fantastic job. He used the characters voice very carefully. The sounds were just like the video game. And i think that was absolutely awesome. The story taking place in New York to the mushroom kingdom is brilliant. Princess peach was the best part of the movie . She had a good way of showing bowser she will not marry a turtle . And toad was the best part of the movie . The rest of the characters including donkey Kong voiced by Seth rogen was so awesome. I hope in the next Mario movie yoshi finds Mario and Luigi and becomes they're pet.",
    },
    {
      username: "folk_egm",
      userUrl: "https://www.imdb.com/user/ur23136302",
      reviewLink: "https://www.imdb.com/review/rw8973472",
      warningSpoilers: false,
      date: "5 April 2023",
      rate: "7",
      helpful: "117 out of 162 found this helpful.",
      title:
        "The Message Of Love Is Sent Directly To The Fanbase, Not To The General Audience.",
      content:
        "This is a movie that feels like a love letter to all the Nintendo fans out there, even if they don't necessarily play Mario anymore. The film delivers a fun and enjoyable experience for viewers by faithfully adapting every aspect of the game into the movie, including the Mario Kart and Donkey Kong franchises. The movie is packed with non-stop action and fast-paced storytelling, leaving little room for some of the more significant elements that fans might have wanted to see. It may not be able to fulfill every fan's wishes, but it's understandable and sets up for a sequel, as there is a post-credits scene.But for general audiences who are not familiar with Mario enough, this might be a movie that is difficult to understand. There may be questions like why does it have to be like this? Why do it this way? Why is the world so strange? This is because the story hardly explains in detail for us to know how the world is. Even though the story is simple and has nothing much. But if you don't think too much, it's an easy and enjoyable movie to watch, with the lovable characters in the style of the works from the studio that made Despicable Me.",
    },
    {
      username: "mj-80986",
      userUrl: "https://www.imdb.com/user/ur68240042",
      reviewLink: "https://www.imdb.com/review/rw8973764",
      warningSpoilers: false,
      date: "5 April 2023",
      rate: "10",
      helpful: "71 out of 95 found this helpful.",
      title: "Brilliant animation and portrayal of the super Mario bros!",
      content:
        "Took my kids for a special sky screening and boy were we excited! At first I was rather skeptical thinking this film won't do any justice to the games. However, I was wrong! This film met our expectation and beyond. I think I enjoyed this film more than my kids. From the moment the film starts it is enjoyable. Good sense of humour and a lot of nice scenes. A lot of laughable moments. Apart from the film being too short it still met my expectations. As a 39 year old who played all the Mario games since childhood, this bought back a lot of fond memories of sleepless nights of playing the Mario games. A must watch film whether you have kids or not.",
    },
    {
      username: "poseyfan",
      userUrl: "https://www.imdb.com/user/ur83316413",
      reviewLink: "https://www.imdb.com/review/rw8973937",
      warningSpoilers: false,
      date: "6 April 2023",
      rate: "9",
      helpful: "71 out of 101 found this helpful.",
      title: "The Mario movie is a great, nostalgic animated film",
      content:
        "The Mario Movie is great! If you are a fan of Nintendo, then you will have a blast. It is sprinkled with a plethora of references and call backs.The voice acting is superb! You can let your reservations on Chris Pratt pass as he is great in this movie. Anya Taylor-Joy brings an optimistic spirit, Charlie Day is good and Seth Rogen is good. But the best by far was Jack Black!! He stole the show. Especially when he sings a certain song!The animation was fantastic. It baffles me how realistic looking they can make everything.Based off of certain parts of the movie, it looks like there will be a sequel on some point, and I'm excited.",
    },
    {
      username: "cruise01",
      userUrl: "https://www.imdb.com/user/ur57691865",
      reviewLink: "https://www.imdb.com/review/rw8980878",
      warningSpoilers: false,
      date: "9 April 2023",
      rate: "10",
      helpful: "29 out of 41 found this helpful.",
      title: "Everything you can ask for in a Mario Bros movie.",
      content:
        "5 out of 5 stars.The Super Mario Bros movie is an awesome animated adventure film that is one of the best adaptation of a video game series. It has everything you can ask for. Its like an open world of nintendo game series like Donkey Kong making an appearance.The film is fast paced. The plot is good. It has a story about the bros. The film features a lot of easter eggs that can hint for more movies. The action sequences are awesome. Bowser is an awesome villain. The animation is beautifully done and stunning. The voice talent is also great.One of the best sequences involving a mario kart chase on a rainbow road is insane. Fans and kids will love the series and love how everything is put together in this film. Overall, i love everything about the film. I can not wait for more.",
    },
    {
      username: "cplushie",
      userUrl: "https://www.imdb.com/user/ur105547839",
      reviewLink: "https://www.imdb.com/review/rw8980194",
      warningSpoilers: false,
      date: "8 April 2023",
      rate: "9",
      helpful: "63 out of 78 found this helpful.",
      title:
        "Don't listen to the critics on rotten tomatoes, this movie is really good.",
      content:
        "As a Mario fan myself it was a very enjoyable and fun action packed movie. While watching I just couldn't wipe the smile off my face. Jack black did an amazing job with voice acting bowser. Everyone did a great job and while I do agree Chris Pratt could have been better i got use to it really quick and im sure pretty much everyone else will too and besides, the Italian accent in the games is great but definitely not meant for a 80 minute movie. The plot is very simple which is good however because a Mario story shouldn't be complex at all and the people at illumination definitely know how the games should be. Speaking of that, you can tell the people behind this movie put a lot of heart into it. Definitely give this a strong recommendation if you like Mario or have childhood memories with Mario in any way or just wanna watch an enjoyable family movie.",
    },
    {
      username: "AdrenalinDragon",
      userUrl: "https://www.imdb.com/user/ur3805352",
      reviewLink: "https://www.imdb.com/review/rw8973546",
      warningSpoilers: false,
      date: "5 April 2023",
      rate: "7",
      helpful: "55 out of 81 found this helpful.",
      title: "Critics are being too harsh for what it is",
      content:
        "I think for what this movie sets out to do, Super Mario Bros. Movie pretty much ticks the boxes of an entertaining, reference fan-service heavy movie. A lot of the jokes are basic sure, but it's just impressive that there is some competency to a Video Game Movie. Sometimes simple and straightforward is the best way to go. Not high art or anything, but it ticks off almost everything for what Mario should be at least. Voice acting wasn't as bad as I thought, and Jack Black was the highlight as expected. Yeah, not gonna win any big awards but judge it for what it is, and yeah by Video Game Movie standards it's one of the best ones easily if you ask me.6.5/10.",
    },
    {
      username: "christiam-51976",
      userUrl: "https://www.imdb.com/user/ur150855562",
      reviewLink: "https://www.imdb.com/review/rw8974043",
      warningSpoilers: false,
      date: "6 April 2023",
      rate: "8",
      helpful: "99 out of 152 found this helpful.",
      title: "Movie not took take seriously",
      content:
        "Some people are taking this movie too seriously. This movie is just supposed to be fun and colorful and not to be taken like a tarantino movie or something. Of course the plot could be improved a bit here and there but it's actually a really fun and entertaining movie when you just enjoy the ride. If you're a big fan of Mario you will absolutely love this movie 100%. I felt like a little kid again when i saw all the characters and easter eggs in every scene. The animation was insanely well done and i believe they could've made the movie a bit longer to expand on the world a bit more and get to know each character more but that's about it.",
    },
    {
      username: "ColinTheGorilla",
      userUrl: "https://www.imdb.com/user/ur150398104",
      reviewLink: "https://www.imdb.com/review/rw8980482",
      warningSpoilers: false,
      date: "9 April 2023",
      rate: "8",
      helpful: "21 out of 28 found this helpful.",
      title: "So much fun",
      content:
        "This movie is so much damn fun and I absolutely loved everything about it. The composing in this movie is some of the best I've ever heard and it fit so well in the movie. The voice acting was pretty good too and I didn't think Chris Pratt would be any good as Mario but he was actually pretty good but Jack Black stole the show as Bowser as he absolutely killed his role. Charlie Day was great too as Luigi as he was probably my 2nd favorite in the movie. The only problem I have with this movie is it felt so quick and I wish it was longer and it's only 90 minutes. Other than that this movie is just a ton of fun and worth the watch.",
    },
    {
      username: "dfreyberg_rocks",
      userUrl: "https://www.imdb.com/user/ur42823875",
      reviewLink: "https://www.imdb.com/review/rw8973163",
      warningSpoilers: true,
      date: "5 April 2023",
      rate: "10",
      helpful: "95 out of 143 found this helpful.",
      title: "Everything You Could Ever Want In a Mario Movie",
      content:
        "I went to see the highly anticipated Super Mario Bros movie tonight with my mum, whom was my gaming buddy back in my childhood days. We'd spend hours playing Mario All-Stars on my dad's SNES, and later on we played on our Mario edition Wii.As a gamer, this movie was a promiseland I wish I could stay in forever. Admittedly, I was sceptical about Chris Pratt voicing everyone's favourite Italian plumber, but he did a superb job and he deserves a lot of praise for his dedication to the role. From learning about power-ups, to fighting against Donkey Kong, and to racing along the infamous Rainbow Road with all the drifts we've all performed countless times on MK8 and its predecessors, this movie is a huge dose of nostalgia for millennials, and a nice introduction for the younger generations.My hat goes off to Mr Jack Black for his awesome job bringing the big, bad Bowser to life on the silver screen. He was the primary reason I wanted to go and see this movie so badly, and he did exceedingly well.",
    },
    {
      username: "erick-hernandez",
      userUrl: "https://www.imdb.com/user/ur32630278",
      reviewLink: "https://www.imdb.com/review/rw8973144",
      warningSpoilers: true,
      date: "5 April 2023",
      rate: "10",
      helpful: "100 out of 149 found this helpful.",
      title: "Fan Service Done RIGHT!",
      content:
        "There are some very minor spoilers ahead, i just want to say that this movie exceeded my expectations! The Critic score should not be taken seriously it's nowhere near a bad nor average movie. There are some things that i didn't like about it but overall i left the theaters with a smile.The Visuals are probably the best Illumination Studios has ever done, very smooth and gorgeous to look at. The human characters like Mario, Luigi and Peach's faces look different from their videogame counterparts and kind of weird at first but you will get used to them and at least their clothing match but on the other hand the animals and creatures from the Mushroom Kingdom like the Koopas, Donkey Kong and Bowser all look very accurate and detailed.The Voice Acting, Sorry but Mario does NOT sound like Mario, at all in this movie! I'm not a fan of Chriss Pratt's acting as Mario. Luigi sounds better but not accurate either, Peach is good i guess and Donkey Kong sounds like Seth Rogen...Yay... Bowser however, gets a straight 10/10 Jack Black actually tried to sound like Bowser and he should be cast again as Bowser in future movies. Long time Mario fans will be surprised to know that Charles Martinet is also in the movie, but not as Mario... The character he got to act for is such a waste and not even worth mentioning to be honest.The Story is not your typical Mario videogame story, it's actually baffling at first how literal they took the Mario \"origin\" story of him being a New York plumber. The movie starts going in the wrong direction but as the movie goes on it becomes better and better and ultimately it worked in the end. The pacing is very fast there is no real character development except for Luigi and maybe Mario but there's just too many relevant characters and not enough time to flesh them out. At least they all have defined personalities.Overall, it's not an Amazing movie but definitely a fun and good first outing by Nintendo and Illumination, it's full of Mario references and just good fan service like a Mario movie should be. Here's hoping future Mario movies!!And 8 but giving it a 10 to even out the hater trolls.",
    },
    {
      username: "keystone_koasters",
      userUrl: "https://www.imdb.com/user/ur158941996",
      reviewLink: "https://www.imdb.com/review/rw8972890",
      warningSpoilers: false,
      date: "5 April 2023",
      rate: "7",
      helpful: "93 out of 137 found this helpful.",
      title: "Solid",
      content:
        "As a Super Mario fan myself, I was hyping this movie up for quite a while. So was it worth that hype? Yes and no. The references, animation, voice acting, and world building are incredible. But, there's a lot of filler and the plot isn't that good either. Despite that, I still really enjoyed it. Though admittedly kinda unnecessary, I really enjoyed watching the Mario Kart section. Same with the Luigi stuff, especially the \"you just got Luigi'd\" line. Though there are some other problems like Toad not really being funny, and this movie is kinda boring sometimes, but it's mostly pretty entertaining. So overall, solid 7/10 movie, must watch for Mario fans but it may not be for everyone else. If you want a Mario film that's an actual masterpiece, go watch Cute Mario Bros The Third Movie. It's not really based on the series, but besides that it's incredible.",
    },
    {
      username: "webslinger-00280",
      userUrl: "https://www.imdb.com/user/ur104673454",
      reviewLink: "https://www.imdb.com/review/rw8973920",
      warningSpoilers: false,
      date: "5 April 2023",
      rate: "8",
      helpful: "43 out of 67 found this helpful.",
      title: "A Near Perfect Adaptation with Iffy Music in Places",
      content:
        "The story was simple, but worked wonders with the excellent characters that perfectly reflected their game counterparts. They even had unique aspects given to them that helped them stand out in all the right ways. The action was phenomenal with great depth and detail that shows how much work was put into this. There were so many nods and references to other classic Nintendo properties that you'd want to go back to find them all. And Charles Martinet is in this with a small but great role. But with all that said, it does mess up its flow with some of the music. Definitely not the original score though, since it mixes the classic music with an epic and emotional tone. But the copyrighted music Illumination probably payed a third of their budget for felt out of place in this film and took me out of the experience a couple times. Other than that, it's an amazing that I'll gladly watch again.",
    },
    {
      username: "Johnny-the-Film-Sentinel-2187",
      userUrl: "https://www.imdb.com/user/ur24085266",
      reviewLink: "https://www.imdb.com/review/rw8973097",
      warningSpoilers: true,
      date: "5 April 2023",
      rate: "7",
      helpful: "43 out of 76 found this helpful.",
      title: "It is as safe as animated movies come.",
      content:
        "**Possible Spoilers**30 years since 1993's fever dream live-action nightmare, The Super Mario Bros. Movie rights the wrongs of the last one; though it's certainly not a perfect movie, it's perfectly fine for what it is, and as family entertainment goes I've seen far worse than it. And with the gorgeous animation, the faithfulness to the games and the music, Chris Pratt and co. Do their best with the same old 'Mario comes to save Peach' storyline being worn thin at this point.Sure the film's problems can be dissected to the nth degree on YouTube retrospectives talking about the movie, but it is what it is and it works where other blockbuster fan-service vehicles have failed (like Terminator: Dark Fate, Ghostbusters 2016 or The Lion King 2019). And Mario (at least Nintendo) has the potential to become a cinematic powerhouse that defies the 'bad' press and reviews (they're more mixed for the movie).The film is basically feature-length comfort food more than anything else; and considering it's a family film that's pretty harmless, I'd say it's done its job more than well. Certainly better than Illumination's other more recent films I'd say.The Super Mario Bros. Movie is the safest kind of cinema, and maybe some people should accept what they see; but not everyone has to. Besides, fun is fun. 3.5/5 stars.P. S. Could this film lead to other stuff like Zelda hitting the big screen? Or maybe even Metroid? Who knows?",
    },
    {
      username: "Legslayer",
      userUrl: "https://www.imdb.com/user/ur160590993",
      reviewLink: "https://www.imdb.com/review/rw8973954",
      warningSpoilers: true,
      date: "6 April 2023",
      rate: "10",
      helpful: "48 out of 74 found this helpful.",
      title: "THE ONE WHO BROKE THE VIDEO CURSE THE MOST!!!",
      content:
        "This Movie was actually really good. It was really well written,The fast paced action scenes were well done like the final battle in Brooklyn. I love the visuals and animation. It's really accurate to modern games and also has references to Previous Mario games and other games made by Nintendo. The soundtrack was really catchy (That even got My all time favorite 80's song Take on Me in the movie and It was playing in the Kong Kingdom scene) Some scenes made me laugh (We don't even need Toilet humor to make people laugh) Charles martinez who voiced Mario and Luigi even was in the movie and the most surprising thing was we get to see Mario and Luigi's Family. I honestly do not see any flaws in the movie not gonna lie. Overall a really great video game movie and the one who broke the video game curse the most.",
    },
    {
      username: "knives123",
      userUrl: "https://www.imdb.com/user/ur11614173",
      reviewLink: "https://www.imdb.com/review/rw8975831",
      warningSpoilers: false,
      date: "6 April 2023",
      rate: "6",
      helpful: "66 out of 110 found this helpful.",
      title: "If You Love Mario or Are Under 10",
      content:
        "I love Mario, and I enjoyed this movie, and so did my 7y/o. But with that out of the way I'll be honest - this movie is quite bad, as movies go. The story is barely present, every scene leads into the next with very little plot or agency - things just happen, characters just need things, that place is suddenly a karting city, that other place has an elevator leading up to a castle straight up a cliffface. The script is probably just screams and the a few catchphrases. It's all held together by nostalgia baiting, references and pandering, wrapped in Minions slapstick. It is all barely coherent. There is also a thing to be said about the music which was murdering classic tunes, some of which is just shockingly bad.Is it a Mario movie? Sure. Is it a fun Mario product for the whole family? Yup. Is it a good movie? No, not really, in fact I'd give it a 6 if I am honest; not awful, but that's about it. So if you are 8 or a Mario fan - sure, you are likely to have a blast. But if you're just a person looking for a fun animation movie wholy uninvested in Mario? Nah, you can probably pass on this.",
    },
    {
      username: "whackamolewv",
      userUrl: "https://www.imdb.com/user/ur164247678",
      reviewLink: "https://www.imdb.com/review/rw8980515",
      warningSpoilers: false,
      date: "9 April 2023",
      rate: "10",
      helpful: "14 out of 19 found this helpful.",
      title: "Any Super Mario fan's dream movie!",
      content:
        "The Super Mario Bros. Movie was amazing! We needed this movie! They did a good job on the CGI animation! And surprisingly, Chris Pratt did an amazing job on voicing Mario in this movie, but obviously we'll need Charles Martinet back for the next Super Mario Brothers game. At first it was unexpected and funny for someone like Chris Pratt to voice Mario, but even when the cast for The Super Mario Bros. Movie was revealed, I had a good feeling Chris Pratt wouldn't do a bad job, because they wouldn't have hired him if Mario didn't fit him. And I also found out Chris Pratt is voicing Garfield for the 2024 Garfield movie, so hopefully he does a good job on voicing Garfield! I honestly get entertained by both Mario and Garfield! Before this movie was announced, I've never imagined Nintendo and Illumination would make an incredible movie like this! It would honestly be funny if Mario met the Minions from Despicable Me because it's an Illumination movie, but something like that wouldn't have to happen because this movie is all about Mario, not Despicable Me. I doubt the people who made this movie are reading this, but if they are, thank you for making this movie!",
    },
    {
      username: "jviaes",
      userUrl: "https://www.imdb.com/user/ur71393619",
      reviewLink: "https://www.imdb.com/review/rw8980491",
      warningSpoilers: true,
      date: "9 April 2023",
      rate: "10",
      helpful: "13 out of 18 found this helpful.",
      title: "Let's A Go!",
      content:
        "This movie was a lot of fun. My 9 year old and I loved it.The animation was superb, the story was very entertaining, and there were moments my mouth was open and I was leaning forward in awe. I may be hyping it up more than it actually is, but I want to have more movies like this.Starting with the animation, very detailed and carefully done. You could see the detail in the fabric of all the clothing, especially the shy guys. There's a sequence where they're traveling under the city of Brooklyn and the water was so realistic. I loved when they got to the \"Mario Kart\" portion because they did not skimp on the details.The story was excellent. They started Mario and Luigi off with humble beginnings and even included their family. There was an actual build up to the adventure which helped buy into the story. Though it did not stick necessarily to the traditional Princess Peach needing rescuing from Bowser, Mario was still his own hero and rose above the put downs being placed on him by Bowser and others. What gave me chills was at the end when Luigi helped Mario and they teamed up to beat Bowser. It was very heartfelt and epic.Though Princess Peach wasn't the traditional damsel in distress, it was evident none of this would have resolved without Mario. Princess Peach was still the apple of Mario's eye, but his brother was also very important to him.Lots of little Easter eggs (I think the Game Cube ring tone may have been my favorite).Two end credit scenes, but really hoping they do more that is at this level.",
    },
    {
      username: "mariotoadman",
      userUrl: "https://www.imdb.com/user/ur104016080",
      reviewLink: "https://www.imdb.com/review/rw8972916",
      warningSpoilers: false,
      date: "5 April 2023",
      rate: "10",
      helpful: "112 out of 162 found this helpful.",
      title: "Nintendo @ Da Best",
      content:
        "I always try to be genuine when it comes to the Big N. Certain years in Nintendo history stand out to me; 2009, 2013, 2017, and now currently one of the best years of Nintendo yet... 2023.I will criticize Nintendo when Nintendo deserve it and praise Nintendo when they deserve it too. This has to be the most self-aware film ever. The film knows exactly who it is representing.If you love Mario, you'll love this film. The animation is beautiful art, the music and soundtrack are fantastic, the whole thing has been handled with immense care. This movie is a love letter and thank you to Super Mario fans.Ignore the critics. They give bad movies good reviews a lot too you know. Peach is a boss and the movie is great.Nintendo wins again. I really felt the love and care, and everyone trying their best w this film. 10/10!!",
    },
    {
      username: "mieriks",
      userUrl: "https://www.imdb.com/user/ur75830806",
      reviewLink: "https://www.imdb.com/review/rw8982532",
      warningSpoilers: true,
      date: "10 April 2023",
      rate: "10",
      helpful: "14 out of 22 found this helpful.",
      title: "Nostalgic perfection",
      content:
        "This movie, about The Super Mario Bros on their journey through the Mushroom Kingdom, is the perfect Mario movie I never thought I could experience!I almost can't describe how enjoyable this was. So many characters and elements joined this incredible journey, and my attention was caught the entire time. I really loved the style and the way this movie was executed. Much was going on, but many things also gave enough time to let us enjoy, be happy and/or laugh about it. And speaking of laughing, I did it many times. The humor was just right! The Lumalee was unexpected hilarious, though!The story was kind of simple, predictable and straight forward, but that's how the Mario games are, aren't they? An interesting thing is that most of this movie was actually kind of about what we usually don't see from the characters in-between the main scenes from the games. We usually only see or hear the same moments or lines from each game, but this movie brought even more detailed personalities and backstories to the characters that really made some depth to the story. The best of all is that this part was done in a fantastic way. It didn't ruin anything! There were also a lot of fan services, but who doesn't love that when you're a big Mario fan? Super Mario Bros. (1985), Donkey Kong (1981) and Mario Kart 8 (2014) were just some parts of the huge amount of Easter Eggs. My favorite part was probably the Mario Kart sequence! There was so much to take in!Even though neither of the well-known characters were voiced by the original actors, the new actors did an incredible job by continuing to make these characters present their original personalities, and bring on the love for the audience. A great casting!The animation and its details and lighting were just insanely impressive! The most recent Mario games have great graphics, but it was both strange and amazing to see these characters in this amazing-looking world by Illumination Entertainment. Everything looked so original and good, and it was just like being inside games in a realistic way. It felt so alive! I also appreciated that there were surprisingly many, epic scenes that really gave some cool and awesome moments in a cinematic way!My props also go to composer Brian Tyler who created, reused and mixed many familiar melodies from many of the games that brought so much nostalgia and good feelings to the experience. There is no Mario without Mario soundtracks!This is my inner child's dream come true, and I'm forever happy that this movie came to life in a perfect way. So much could have gone wrong, but directors Michael Jelenic and Aaron Horvath made this successful in every way, and therefore, this is my favorite animation movie of all time!",
    },
    {
      username: "educunhaholanda",
      userUrl: "https://www.imdb.com/user/ur113594588",
      reviewLink: "https://www.imdb.com/review/rw8980378",
      warningSpoilers: false,
      date: "8 April 2023",
      rate: "7",
      helpful: "11 out of 15 found this helpful.",
      title: "Fun and that's all",
      content:
        "If you only watch the movie with the intention of having fun, you will certainly have a good experience with Mario. However the plot is quite bland and the movie runs at a very fast pace between one scene and another, hampering the progress of the story.Also, if you haven't played the Mario games, you'll fail immeasurably to pick up the game references that are scattered throughout the movie, and there are many of them. For anyone who's a Mario fan, this movie is literally fan service and it's no wonder why they're giving it a 10.For me, this movie doesn't lived up to the hype, but for a Mario fan, it certainly did.",
    },
    {
      username: "cheapbird-58418",
      userUrl: "https://www.imdb.com/user/ur90114243",
      reviewLink: "https://www.imdb.com/review/rw8984565",
      warningSpoilers: false,
      date: "10 April 2023",
      rate: "8",
      helpful: "7 out of 9 found this helpful.",
      title: "Nostalgia at it's best",
      content:
        "This film is no 'original' idea like Despicable me...... it's not meant to be!!!It's simply a Mario film for the fans and sticks with all game themes beautifully (again, as it should be).Voices are perfectly cast....esp bowser (Jack Black).The plot was simple and totally expected. As it should have been! The game features transferred to the movie perfectly. Adult puns and jokes in there as well as ones the kids will get.Cheeky, little, cute Post Scene Credit (which as Marvel fans we know to hang around to see if there was one).Our seven year old son thought it was amazing and he only knows Mario Kart in the gaming world. So it's appealing all round for adults (nostalgia) for kids (pure fun).",
    },
  ],
};
